# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  host: <%= ENV.fetch("PG_HOST") {"127.0.0.1"} %>
  port: <%= ENV.fetch("PG_PORT") {5432} %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USER") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: devhub_development

test:
  <<: *default
  database: devhub_test